services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_dB: car_sales_db
      POSTGRES_PGADMIN: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - webapi_netwrok
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    ports:
      - "8090:80"
    networks:
      - webapi_netwrok
    volumes:
      - pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: alirezaabdolmaleki80@gmail.com
      PGADMIN_DEFAULT_PASSWORD: alireza80
    depends_on:
      - postgres
    restart: unless-stopped
  
  redis:
    image: redis:latest
    container_name: redis_container
    command: ["redis-server", "/etc/redis/redis.conf"]
    volumes:
      - ./redis/redis.conf:/etc/redis/redis.conf
      - redis:/etc/redis.conf
      - redis:/data
    ports:
      - "6379:6379"
    networks:
      - webapi_netwrok
    restart: unless-stopped

volumes:
  postgres:
  pgadmin:
  redis:

networks:
  webapi_netwrok:
    driver: "bridge"
